repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.7.4
          - pydantic-mypy>=2.7.4
          - types-pyyaml>=6.0.12
          - alpaca-py>=0.30.0
          - structlog>=24.4.0
